import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import SurfaceFormScript from "./SurfaceFormScript";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="/surface_tag.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <SurfaceFormScript
          formUrl="https://dev.withsurface.com/s/cmi4bpjy40001kz0b96vku8fk" // Replace this with a Surface Form URL
          embedType="popup"
          popupSize="medium" // "small", "medium", "large"
          buttonClassName="surface-form-button"
        />
      </body>
    </html>
  );
}
